# Generated by Django 2.2 on 2022-05-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='codigo',
            field=models.IntegerField(default=0),
        ),
    ]
