# Generated by Django 2.2 on 2022-06-13 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220613_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colaboradors', to='core.Banco'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='comuna',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='cuenta_banco',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='direccion',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='fecha_nacimiento',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='telefono',
            field=models.TextField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='tipo_cuenta_banco',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='banco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedors', to='core.Banco'),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='colaboradores',
            field=models.ManyToManyField(blank=True, related_name='terrenos', to='core.Colaborador'),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terrenos', to='core.Proyecto'),
        ),
        migrations.AlterField(
            model_name='terrenomovilizacion',
            name='conductores',
            field=models.ManyToManyField(related_name='terrenomovilizacions', to='core.Colaborador'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuelos', to='core.Colaborador'),
        ),
    ]
